# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(
  dependencies=[
    '3rdparty:junit',
    '3rdparty/jvm/pl/pragmatists:JUnitParams',
  ],
)
